import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import { CartProvider } from './components/CartContext';
import './styles.css';
import './dashboard.css';
import './enhancements.css';
import './admin.css';
import './hotel.css';
import './about.css';
import './about-overrides.css';
import './theme.css';
import './commerce.css';
import './commerce-overrides.css';
import './product-popup.css';
import './inventory.css';
import './staff-inventory.css';
import './cart.css';
import './hotel-tracking.css';
import './staff-portal.css';
import './workforce.css';
import './feedback.css';
import './admin-motion.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><CartProvider><App /></CartProvider></BrowserRouter></React.StrictMode>);
