import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import './styles.css';
import './dashboard.css';
import './enhancements.css';
import './admin.css';
import './hotel.css';
import './about.css';
import './about-overrides.css';
import './theme.css';
import './commerce.css';
import './commerce-overrides.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App /></BrowserRouter></React.StrictMode>);
