import { Eye, Heart, Lightbulb, ShieldCheck, Sparkles, Target, UserRoundCheck } from 'lucide-react';
import { Img, SectionTitle } from '../components/UI';

export default function AboutPage(){return <>
 <section className="about-new-hero"><div><span>VỀ PETTECH CARE CENTER</span><h1>Chăm sóc bằng công nghệ,<br/><em>kết nối bằng yêu thương.</em></h1><p>PetTech xây dựng một hệ sinh thái chăm sóc thú cưng minh bạch, tiện lợi và cá nhân hóa để mỗi chủ nuôi luôn an tâm dù ở bất cứ đâu.</p></div><Img src="https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=90" alt="PetTech Care Center"/></section>
 <section className="section about-goal"><div className="about-goal-art"><Img src="https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=1000&q=85" alt="Mục tiêu PetTech"/><span><Target/><b>01</b></span></div><div><SectionTitle center={false} eyebrow="MỤC TIÊU" title="Biến sự an tâm thành một trải nghiệm có thể nhìn thấy"/><p>PetTech hướng tới việc xóa bỏ khoảng cách giữa chủ nuôi và thú cưng trong suốt quá trình chăm sóc. Mọi lịch hẹn, tình trạng sức khỏe, hoạt động lưu trú và khoảnh khắc của bé đều được kết nối trên một nền tảng duy nhất.</p><div className="goal-points"><span><b>Minh bạch</b>Theo dõi rõ từng hoạt động chăm sóc</span><span><b>Liền mạch</b>Từ đặt lịch đến thanh toán và báo cáo</span><span><b>Cá nhân hóa</b>Mỗi bé có một hồ sơ chăm sóc riêng</span></div></div></section>
 <section className="about-pillars section"><SectionTitle eyebrow="ĐỊNH HƯỚNG CỦA CHÚNG TÔI" title="Hôm nay tận tâm, ngày mai dẫn đầu" desc="Sứ mệnh và tầm nhìn là kim chỉ nam cho mọi dịch vụ, sản phẩm và quyết định tại PetTech."/><div className="mission-vision"><article><span><Heart/></span><small>02 · SỨ MỆNH</small><h2>Giúp chủ nuôi an tâm hơn mỗi ngày</h2><p>Kiến tạo một hệ sinh thái chăm sóc thú cưng minh bạch, tiện lợi và cá nhân hóa; kết hợp chuyên môn, sự tận tâm và công nghệ để mỗi bé được chăm sóc đúng nhu cầu.</p><ul><li>Đặt sức khỏe và sự thoải mái của thú cưng lên đầu</li><li>Cung cấp thông tin trung thực, kịp thời cho chủ nuôi</li><li>Đồng hành xuyên suốt mọi giai đoạn phát triển</li></ul></article><article><span><Eye/></span><small>03 · TẦM NHÌN</small><h2>Nền tảng chăm sóc thú cưng thông minh hàng đầu Việt Nam</h2><p>PetTech hướng tới một tương lai nơi dữ liệu sức khỏe, dịch vụ thực tế và kết nối trực tuyến cùng hoạt động trong một hệ sinh thái thống nhất, an toàn và dễ tiếp cận.</p><ul><li>Tiên phong ứng dụng công nghệ vào chăm sóc thú cưng</li><li>Xây dựng tiêu chuẩn dịch vụ minh bạch và chuyên nghiệp</li><li>Mở rộng cộng đồng chủ nuôi văn minh, khoa học</li></ul></article></div></section>
 <section className="section about-values"><SectionTitle eyebrow="04 · GIÁ TRỊ CỐT LÕI" title="Những giá trị chúng tôi luôn gìn giữ" desc="Không chỉ là lời hứa thương hiệu — đây là tiêu chuẩn trong từng khoảnh khắc chăm sóc."/><div className="value-grid">{[[ShieldCheck,'An toàn','Quy trình chuẩn hóa, môi trường sạch và dữ liệu được bảo mật.'],[Heart,'Tận tâm','Đối xử với mỗi thú cưng như một thành viên trong gia đình.'],[Sparkles,'Minh bạch','Chủ nuôi luôn biết bé đang được chăm sóc như thế nào.'],[UserRoundCheck,'Cá nhân hóa','Dịch vụ được điều chỉnh theo sức khỏe và tính cách từng bé.'],[Lightbulb,'Đổi mới','Công nghệ được ứng dụng để giải quyết nhu cầu thực tế.']].map(([I,t,d]:any,i)=><article key={t}><span>0{i+1}</span><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section className="about-quote"><p>“Chúng tôi không chỉ chăm sóc thú cưng,<br/>chúng tôi giúp chủ nuôi luôn yên tâm dù ở bất cứ đâu.”</p><span>PETTECH CARE CENTER</span></section>
 </>}
