import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { BarChart3, CalendarDays, CircleDollarSign, Hotel, PackageOpen, PawPrint, Search, Settings, Sparkles, TrendingUp, UserRound, Users, WalletCards } from 'lucide-react';
import { productGroups } from './CommercePages';
import { changeStock, readInventory } from '../components/inventoryStore';

const nav=[[BarChart3,'Tổng quan','/admin'],[CalendarDays,'Đơn hàng','/admin/orders'],[Users,'Khách hàng','/admin/customers'],[PawPrint,'Thú cưng','/admin/pets'],[UserRound,'Nhân viên & Ca làm','/admin/staff'],[Hotel,'Pet Hotel','/admin/hotel'],[PackageOpen,'Kho sản phẩm','/admin/inventory'],[CircleDollarSign,'Doanh thu','/admin/finance'],[WalletCards,'Chi phí','/admin/expenses'],[Sparkles,'Combo','/admin/memberships'],[TrendingUp,'Analytics','/admin/analytics']];
const products=productGroups.flatMap(group=>group.items.map((row:any[])=>({id:Number(row[0]),category:group.title,type:String(row[1]),name:String(row[2]),unit:String(row[3]),price:Number(row[4])})));
const money=(n:number)=>`${n.toLocaleString('vi-VN')}đ`;

export default function AdminInventory(){
 const [data,setData]=useState(readInventory);const [query,setQuery]=useState('');
 const shown=products.filter(x=>`${x.name} ${x.type} ${x.category}`.toLowerCase().includes(query.toLowerCase()));
 const totalStock=Object.values(data.stock).reduce((a,b)=>a+b,0);const totalSold=Object.values(data.sold).reduce((a,b)=>a+b,0);const totalRevenue=Object.values(data.revenue).reduce((a,b)=>a+b,0);const low=products.filter(x=>(data.stock[x.id]||0)<=5).length;
 const update=(id:number,delta:number)=>setData(changeStock(id,delta));
 const top=useMemo(()=>[...products].sort((a,b)=>(data.sold[b.id]||0)-(data.sold[a.id]||0)).slice(0,5),[data]);
 return <div className="dash admin-system"><aside><Link className="logo" to="/"><span><PawPrint/></span><b>PAWFECT<small>ADMIN CENTER</small></b></Link><p className="role">QUẢN TRỊ VIÊN</p>{nav.map(([Icon,label,path]:any)=><Link className={`side-link ${path==='/admin/inventory'?'active':''}`} to={path} key={label}><Icon/>{label}</Link>)}<div className="side-bottom"><Link className="side-link" to="/admin/settings"><Settings/> Cài đặt hệ thống</Link></div></aside><div className="dash-main"><div className="dash-top"><div className="dash-search"><Search/> Tìm sản phẩm, mã hàng...</div></div><div className="dash-content"><div className="welcome"><div><p>KHO & BÁN LẺ</p><h1>Quản lý sản phẩm chăm sóc</h1><span>Theo dõi tồn kho, lượt mua và doanh thu bán sản phẩm.</span></div></div><div className="inventory-kpis"><article><PackageOpen/><span>Tổng tồn kho<b>{totalStock}</b><small>18 mã sản phẩm</small></span></article><article><TrendingUp/><span>Đã bán<b>{totalSold}</b><small>Tổng lượt mua</small></span></article><article><CircleDollarSign/><span>Doanh thu sản phẩm<b>{money(totalRevenue)}</b><small>Ghi nhận từ giỏ hàng</small></span></article><article className={low?'warning':''}><WalletCards/><span>Sắp hết hàng<b>{low}</b><small>Tồn kho ≤ 5</small></span></article></div><div className="inventory-layout"><section className="panel admin-table"><div className="panel-head"><div><h3>Danh sách tồn kho</h3><p>Nhập thêm hoặc điều chỉnh số lượng từng sản phẩm</p></div><label className="inventory-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm sản phẩm..."/></label></div><table><thead><tr><th>Mã</th><th>Sản phẩm</th><th>Nhóm</th><th>Giá</th><th>Tồn kho</th><th>Đã bán</th><th>Doanh thu</th><th>Điều chỉnh</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><b>SP-{x.id}</b></td><td><b>{x.name}</b><small>{x.type} · {x.unit}</small></td><td>{x.category}</td><td>{money(x.price)}</td><td><span className={`inventory-stock ${(data.stock[x.id]||0)<=5?'low':''}`}>{data.stock[x.id]||0}</span></td><td>{data.sold[x.id]||0}</td><td><b>{money(data.revenue[x.id]||0)}</b></td><td><div className="inventory-adjust"><button onClick={()=>update(x.id,-1)}>−</button><button onClick={()=>update(x.id,1)}>+</button><button onClick={()=>update(x.id,10)}>+10 nhập kho</button></div></td></tr>)}</tbody></table></section><aside className="panel inventory-top"><h3>Sản phẩm bán chạy</h3>{top.map((x,i)=><div key={x.id}><i>{i+1}</i><span><b>{x.name}</b><small>{data.sold[x.id]||0} lượt mua</small></span><strong>{money(data.revenue[x.id]||0)}</strong></div>)}</aside></div></div></div></div>
}
