import { BarChart3, CalendarDays, CircleDollarSign, Hotel, LogOut, PackageOpen, PawPrint, Search, Settings, Sparkles, TrendingUp, UserRound, Users, WalletCards } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import CountUp from '../components/CountUp';

const nav=[[BarChart3,'Tổng quan','/admin'],[CalendarDays,'Đơn hàng','/admin/orders'],[Users,'Khách hàng','/admin/customers'],[PawPrint,'Thú cưng','/admin/pets'],[UserRound,'Nhân viên & Ca làm','/admin/staff'],[Hotel,'Pet Hotel','/admin/hotel'],[PackageOpen,'Kho sản phẩm','/admin/inventory'],[WalletCards,'Chi phí','/admin/expenses'],[Sparkles,'Combo','/admin/memberships'],[TrendingUp,'Analytics','/admin/analytics']];
const revenue=[210,260,245,330,390,472];
const stats=[[CircleDollarSign,'Tổng doanh thu',2840,'+18,2%'],[CalendarDays,'Booking',1248,'+12,5%'],[Users,'Khách hàng',862,'+8,4%'],[PawPrint,'Thú cưng',1036,'+11,1%']];

export default function AdminOverview(){
 const navigate=useNavigate();
 const logout=()=>{localStorage.clear();navigate('/')};
 return <div className="dash admin-system admin-animated"><aside><Link className="logo" to="/"><span><PawPrint/></span><b>PAWFECT<small>ADMIN CENTER</small></b></Link><p className="role">QUẢN TRỊ VIÊN</p>{nav.map(([Icon,label,path]:any)=><Link className={`side-link ${path==='/admin'?'active':''}`} to={path} key={label}><Icon/>{label}</Link>)}<div className="side-bottom"><Link className="side-link" to="/admin/settings"><Settings/> Cài đặt hệ thống</Link><button onClick={logout}><LogOut/> Đăng xuất</button></div></aside><div className="dash-main"><div className="dash-top"><div className="dash-search"><Search/> Tìm kiếm trong hệ thống...</div></div><div className="dash-content">
  <div className="welcome"><div><p>TỔNG QUAN KINH DOANH</p><h1>Chào buổi sáng, Quản trị viên</h1><span>Trung tâm đang vận hành ổn định. Doanh thu tăng 18,2% tháng này.</span></div><select><option>6 tháng gần nhất</option></select></div>
  <div className="stat-grid">{stats.map(([Icon,t,v,s]:any,i)=><div className="stat-card" style={{animationDelay:`${i*90}ms`}} key={t}><span><Icon/></span><p>{t}</p><b><CountUp end={v} format={n=>t==='Tổng doanh thu'?`${(n/1000).toLocaleString('vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2})} tỷ`:Math.round(n).toLocaleString('vi-VN')}/></b><small className="up"><TrendingUp/> {s} so với kỳ trước</small></div>)}</div>
  <div className="admin-visual-grid"><section className="panel admin-revenue-visual"><div className="panel-head"><div><h3>Doanh thu theo tháng</h3><p>Đơn vị: triệu VNĐ</p></div><b><span><CountUp end={472}/> triệu</span><small>tháng này</small></b></div><div className="revenue-bars">{revenue.map((v,i)=><div key={v}><span style={{height:`${v/5}px`,animationDelay:`${250+i*90}ms`}}><b><CountUp end={v} duration={900+i*100}/></b></span><small>T{i+1}</small></div>)}</div></section><section className="panel admin-hotel-visual"><div className="panel-head"><div><h3>Công suất Pet Hotel</h3><p>Cập nhật theo thời gian thực</p></div><Link to="/admin/hotel">Xem chi tiết</Link></div><div className="occupancy-ring"><div><b><CountUp end={78}/>%</b><span><CountUp end={26}/>/34 phòng</span></div></div><p><span>● Đang sử dụng <b><CountUp end={26}/></b></span><span>● Còn trống <b><CountUp end={8}/></b></span></p></section></div>
  <div className="finance-kpis overview-finance-kpis">{[[CircleDollarSign,'Doanh thu dịch vụ',472000000,'+18,2%'],[WalletCards,'VAT đầu ra 8%',37760000,'Cần kê khai'],[WalletCards,'Chi phí vận hành',286400000,'+6,4%'],[TrendingUp,'Lợi nhuận trước thuế',185600000,'Biên 39,3%']].map(([Icon,title,value,note]:any)=><div key={title}><span><Icon/></span><p>{title}</p><b><CountUp end={value} format={n=>`${Math.round(n).toLocaleString('vi-VN')}đ`}/></b><small>{note}</small></div>)}</div>
  <div className="finance-grid overview-finance-grid"><div className="panel finance-breakdown"><h3>Cơ cấu doanh thu</h3>{[['Pet Hotel','128,4 triệu',27],['Grooming','96,8 triệu',21],['Spa cao cấp','74,2 triệu',16],['Chăm sóc sức khỏe','68,6 triệu',15],['Combo & dịch vụ khác','104 triệu',21]].map((x,i)=><div key={x[0]}><p><span>{x[0]}</span><b>{x[1]}</b></p><i><em style={{width:`${x[2]}%`,animationDelay:`${350+i*90}ms`}}/></i></div>)}</div><div className="panel vat-report"><div><h3>Báo cáo VAT tháng 6/2026</h3><p>VAT thu từ khách hàng được theo dõi riêng, không tính là doanh thu thuần.</p></div><div><span>Doanh thu chưa VAT<b>472.000.000đ</b></span><span>VAT đầu ra 8%<b>37.760.000đ</b></span><span>Tổng tiền thu khách hàng<b>509.760.000đ</b></span></div></div></div>
  <div className="admin-home-grid"><section className="panel"><div className="panel-head"><div><h3>Booking gần đây</h3><p>Các hoạt động mới nhất</p></div><Link to="/admin/orders">Xem tất cả</Link></div>{[['PF-00125','Mochi · Grooming Gold','09:00','Đã xác nhận'],['PF-00126','Bella · Pet Hotel Gold','10:30','Đang phục vụ'],['PF-00127','Bông · Spa Premium','13:00','Chờ xác nhận'],['PF-00128','Milo · Khám sức khỏe','15:00','Đã xác nhận']].map(x=><div className="admin-home-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><time>{x[2]}</time><em>{x[3]}</em></div>)}</section><section className="panel top-services"><div className="panel-head"><div><h3>Dịch vụ nổi bật</h3><p>Theo doanh thu tháng này</p></div></div>{[['Pet Hotel','128,4 triệu',88],['Grooming','96,8 triệu',70],['Spa cao cấp','74,2 triệu',55],['Chăm sóc sức khỏe','52,6 triệu',40]].map((x,i)=><div key={x[0]}><i>{i+1}</i><p><b>{x[0]}</b><span><em style={{width:x[2]+'%',animationDelay:`${650+i*100}ms`}}/></span></p><strong>{x[1]}</strong></div>)}</section></div>
 </div></div></div>;
}
