import { useParams } from 'react-router-dom';
import { Check, Clock3, HeartPulse, Hotel, Scissors, Shield, Sparkles } from 'lucide-react';
import { Button, Img, SectionTitle } from '../components/UI';

export const serviceData=[
 {slug:'grooming',name:'Grooming',desc:'Tắm, sấy, vệ sinh và cắt tỉa theo giống.',icon:Scissors,image:'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1000&q=85',duration:'60–120 phút',tiers:[['Silver','119.000đ','Tắm, sấy, vệ sinh tai và cắt móng'],['Gold','219.000đ','Silver + cắt tỉa tạo kiểu, dưỡng lông'],['Premium','319.000đ','Gold + massage, phục hồi lông chuyên sâu']]},
 {slug:'spa',name:'Spa',desc:'Liệu trình thư giãn, chăm sóc da và phục hồi lông.',icon:Sparkles,image:'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1000&q=85',duration:'75–120 phút',tiers:[['Silver','119.000đ','Tắm thảo mộc và massage 15 phút'],['Gold','299.000đ','Silver + ủ dưỡng da lông chuyên sâu'],['Premium','419.000đ','Gold + liệu trình phục hồi và xịt dưỡng cao cấp']]},
 {slug:'pet-hotel',name:'Pet Hotel',desc:'Phòng riêng tiện nghi, camera và báo cáo mỗi ngày.',icon:Hotel,image:'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=1000&q=85',duration:'Theo ngày / đêm',tiers:[['Silver','289.000đ/ngày','Phòng tiêu chuẩn, 2 bữa và 1 lần vui chơi'],['Gold','389.000đ/ngày','Phòng rộng, camera 24/7 và 2 lần vui chơi'],['Premium','519.000đ/ngày','Phòng VIP, báo cáo 3 lần/ngày, chăm sóc 1:1']]},
 {slug:'health-care',name:'Chăm sóc sức khỏe',desc:'Khám tổng quát và theo dõi sức khỏe định kỳ.',icon:HeartPulse,image:'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1000&q=85',duration:'30–60 phút',tiers:[['Silver','189.000đ','Khám tổng quát cơ bản'],['Gold','299.000đ','Khám tổng quát + tư vấn dinh dưỡng'],['Premium','499.000đ','Gold + xét nghiệm cơ bản, hồ sơ sức khỏe số + sổ giun']]}
];

export function Services(){return <><PageHero tag="DỊCH VỤ PAWFECT" title="Bốn dịch vụ cốt lõi, trọn vẹn yêu thương" desc="Tập trung vào những dịch vụ thiết thực, minh bạch về quy trình, thời gian và chi phí."/><section className="section"><div className="services-grid">{serviceData.map(s=>{const I=s.icon;return <article className="service-card" key={s.slug}><div className="service-image"><Img src={s.image} alt={s.name}/><span><I/></span></div><div><h3>{s.name}</h3><p>{s.desc}</p><p className="duration"><Clock3/> {s.duration}</p><b>Từ {s.tiers[0][1]}</b><Button to={`/services/${s.slug}`} variant="text">Xem chi tiết</Button></div></article>})}</div></section></>}
export function ServiceDetail(){const {slug}=useParams();const s=serviceData.find(x=>x.slug===slug)||serviceData[0];const I=s.icon;return <><section className="service-detail-hero"><div><span className="eyebrow">DỊCH VỤ PAWFECT</span><h1>{s.name}</h1><p>{s.desc} Mỗi bước đều được ghi nhận để chủ nuôi dễ dàng theo dõi.</p><div><span><Clock3/> {s.duration}</span><span><Shield/> Quy trình an toàn</span></div><Button to="/booking">Chọn dịch vụ này</Button></div><Img src={s.image} alt={s.name}/></section><section className="section detail-process"><SectionTitle eyebrow="QUY TRÌNH DỊCH VỤ" title="Bé sẽ được chăm sóc như thế nào?"/><div className="four-grid">{[['01','Tiếp nhận & tư vấn','Kiểm tra tình trạng, thói quen và ghi nhận yêu cầu riêng.'],['02','Thực hiện dịch vụ','Chuyên viên tiến hành theo đúng cấp độ đã chọn.'],['03','Kiểm tra chất lượng','Đánh giá kết quả, sức khỏe và mức độ thoải mái của bé.'],['04','Bàn giao & báo cáo','Gửi hình ảnh, lưu hồ sơ và hướng dẫn chăm sóc tại nhà.']].map(x=><div className="number-card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section><section className="section tier-section"><SectionTitle eyebrow="3 CẤP ĐỘ CHĂM SÓC" title={`Chọn gói ${s.name} phù hợp`}/><div className="tier-grid">{s.tiers.map((t,i)=><div className={i===1?'tier featured':'tier'} key={t[0]}><span>{i===1?'ĐƯỢC CHỌN NHIỀU':'GÓI DỊCH VỤ'}</span><I/><h3>{t[0]}</h3><b>{t[1]}</b><p>{t[2]}</p><ul><li><Check/> Tư vấn trước dịch vụ</li><li><Check/> Ảnh cập nhật sau hoàn thành</li><li><Check/> Lưu vào hồ sơ chăm sóc</li></ul><Button to="/booking" variant={i===1?'primary':'outline'}>Chọn {t[0]}</Button></div>)}</div></section></>}
export function Pricing(){return <><PageHero tag="BẢNG GIÁ DỊCH VỤ" title="Giá rõ ràng cho từng cấp độ chăm sóc" desc="Silver cho nhu cầu cơ bản, Gold cân bằng quyền lợi và Premium cho trải nghiệm toàn diện."/><section className="section pricing-detail"><div className="pricing-legend"><span><b>Silver</b>Tiết kiệm, đủ nhu cầu cơ bản</span><span><b>Gold</b>Nâng cao, được chọn nhiều nhất</span><span><b>Premium</b>Chăm sóc toàn diện</span></div>{serviceData.map(s=>{const I=s.icon;return <div className="pricing-service" key={s.slug}><div className="pricing-name"><I/><div><h3>Bảng giá dịch vụ {s.name}</h3><p>{s.duration}</p></div><Button to={`/services/${s.slug}`} variant="text">Xem chi tiết</Button></div><div className="pricing-tiers">{s.tiers.map((t,i)=><div className={i===1?'best':''} key={t[0]}><span>{t[0]}</span><b>{t[1]}</b><p>{t[2]}</p><Button to="/booking" variant={i===1?'primary':'outline'}>Chọn gói</Button></div>)}</div></div>})}</section></>}

const combos=[['Combo Sạch Xinh','279.000đ','Grooming Silver + Spa Silver'],['Combo Tỏa Sáng','139.000đ','Grooming Gold + Spa Gold'],['Combo Kỳ Nghỉ An Tâm','1.299.000đ','3 ngày Pet Hotel Gold + 1 Grooming'],['Combo Khỏe & Đẹp','469.000đ','Khám sức khỏe Gold + Grooming Gold'],['Combo Đón Tận Nhà','399.000đ','Đưa đón 2 chiều + Spa Gold'],['Combo Premium Day','859.000đ','Grooming Premium + Spa Premium + đưa đón']];
export function Membership(){return <><PageHero tag="COMBO CHĂM SÓC" title="Kết hợp nhiều dịch vụ, tiết kiệm nhiều hơn" desc="Không cần mua membership — chọn đúng combo hoặc kỳ hạn phù hợp với lịch chăm sóc của bé."/><section className="section combo-section"><SectionTitle eyebrow="II · BẢNG GIÁ DỊCH VỤ COMBO" title="Một lần đặt, trọn gói yêu thương"/><div className="combo-grid">{combos.map((c,i)=><div className={i===1?'combo featured':'combo'} key={c[0]}><span>{i===1?'PHỔ BIẾN':'COMBO'}</span><h3>{c[0]}</h3><p>{c[2]}</p><div><b>{c[1]}</b></div><Button to="/booking" variant={i===1?'primary':'outline'}>Chọn combo</Button></div>)}</div></section><section className="section term-pricing"><SectionTitle eyebrow="III · GÓI ĐĂNG KÝ THEO KỲ" title="Gói Chăm Sóc Tiêu Chuẩn" desc="Áp dụng linh hoạt cho combo hoặc dịch vụ chăm sóc trong thời hạn đăng ký."/><div className="term-plan"><div className="term-inclusions"><span>ĐỊNH MỨC SỬ DỤNG MỖI THÁNG</span><h3>Chăm sóc đều đặn, chi phí tối ưu</h3><p><Check/> 2 lần Grooming Silver mỗi tháng</p><p><Check/> 2 lần Spa Silver mỗi tháng</p><small>Tổng giá trị gốc: <b>476.000đ/tháng</b></small></div><div className="term-options"><article><span>3 THÁNG</span><b>1.356.000đ</b><em>Giảm 5%</em><p>Sử dụng linh hoạt trong 3 tháng</p><Button to="/booking" variant="outline">Đăng ký</Button></article><article><span>6 THÁNG</span><b>2.570.000đ</b><em>Giảm 10%</em><p><Check/> Tặng 1 lần Spa Silver</p><Button to="/booking">Đăng ký</Button></article><article className="featured"><span>12 THÁNG</span><b>4.855.000đ</b><em>Giảm 15%</em><p><Check/> Tặng 1 Grooming Silver</p><p><Check/> Ưu tiên sắp xếp lịch hẹn</p><Button to="/booking">Đăng ký</Button></article></div></div></section></>}
function PageHero({tag,title,desc}:{tag:string,title:string,desc:string}){return <section className="page-hero"><span>{tag}</span><h1>{title}</h1><p>{desc}</p></section>}
