import { Activity, CalendarCheck, Camera, CheckCircle2, Clock3, HeartPulse, Hotel, QrCode, ShieldCheck, Smartphone, Sparkles, Syringe } from 'lucide-react';
import { Button, Img, Rating, SectionTitle } from '../components/UI';
const services=[['Grooming','Tắm, sấy và tạo kiểu chỉn chu','https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=85'],['Spa thư giãn','Massage và chăm sóc da lông chuyên sâu','https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=900&q=85'],['Pet Hotel','Không gian lưu trú an toàn, tiện nghi','https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=900&q=85']];
const feedbacks=[
 ['Nguyễn Minh Anh','Mẹ của Mochi','Dịch vụ rất chuyên nghiệp. Mình có thể theo dõi Mochi qua camera nên hoàn toàn yên tâm trong suốt kỳ nghỉ.','MA'],
 ['Trần Hoàng Nam','Ba của Bắp','Bé Bắp được grooming rất kỹ, lông mềm và thơm lâu. Nhân viên còn hướng dẫn chăm sóc tại nhà rất tận tình.','HN'],
 ['Lê Thảo Vy','Mẹ của Bella','Nhật ký chăm sóc được cập nhật đều đặn kèm hình ảnh. Đây là điều mình thích nhất khi gửi Bella tại PAWFECT.','TV'],
 ['Phạm Gia Huy','Ba của Milo','Đặt lịch nhanh, bảng giá rõ ràng và không có chi phí phát sinh. Milo về nhà vẫn vui vẻ, không hề căng thẳng.','GH'],
 ['Võ Ngọc Linh','Mẹ của Miu','Spa sạch sẽ, nhân viên nhẹ nhàng với mèo. Miu vốn nhát người nhưng lần này hợp tác rất tốt.','NL'],
 ['Đặng Quốc Bảo','Ba của Đậu','Combo dịch vụ hợp lý và tiết kiệm. Hồ sơ của bé được lưu đầy đủ nên lần sau không phải khai lại thông tin.','QB']
];
export default function Home(){return <>
 <section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> Hệ sinh thái chăm sóc thú cưng 4.0</span><h1>Chăm sóc thông minh,<br/><em>an tâm mọi lúc.</em></h1><p className="eyebrow">An tâm gửi gắm – Minh bạch từng khoảnh khắc</p><p>PetTech kết nối spa, khách sạn thú cưng và hồ sơ sức khỏe điện tử trong một trải nghiệm minh bạch, cá nhân hóa.</p><div className="hero-actions"><Button to="/login">Đặt lịch ngay</Button><Button to="/services" variant="text">Khám phá dịch vụ</Button></div><Rating/></div><div className="hero-visual"><div className="hero-blob"></div><Img src="https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=1100&q=90" alt="Chủ nuôi hạnh phúc bên thú cưng"/><div className="float-card health"><HeartPulse/><span><b>Hồ sơ sức khỏe</b><small>Được cập nhật hôm nay</small></span><CheckCircle2/></div><div className="float-card camera"><span className="pulse">●</span><span><b>Live Camera 24/7</b><small>Đang phát trực tiếp</small></span></div></div><div className="trust-strip"><span><ShieldCheck/> Quy trình an toàn</span><span><Activity/> Theo dõi sức khỏe</span><span><Camera/> Camera trực tuyến</span><span><Clock3/> Hỗ trợ 24/7</span></div></section>
 <section className="problem section"><SectionTitle eyebrow="NỖI LO CỦA CHỦ NUÔI" title="Yêu thương là chưa đủ khi bạn không thể luôn ở bên" desc="Những khoảng trống trong cách chăm sóc truyền thống khiến người nuôi khó thực sự an tâm."/><div className="four-grid">{[['01','Quá bận rộn','Không đủ thời gian duy trì lịch chăm sóc đều đặn.'],['02','Thiếu minh bạch','Không biết thú cưng thực sự thế nào khi gửi lại.'],['03','Dễ quên lịch','Bỏ lỡ vaccine, tẩy giun hoặc lịch tái khám.'],['04','Dịch vụ rời rạc','Thông tin phân tán, thiếu một hồ sơ cá nhân hóa.']].map(x=><div className="number-card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>
 <section className="solution section"><div className="split"><div><SectionTitle center={false} eyebrow="GIẢI PHÁP TOÀN DIỆN" title="Mọi điều thú cưng cần, trong một hệ sinh thái" desc="Từ lúc đặt lịch đến khi đón bé về, mọi trải nghiệm đều liền mạch và được ghi nhận."/><Button to="/about" variant="outline">Hiểu thêm về PetTech</Button></div><div className="solution-grid">{[[CalendarCheck,'Đặt lịch trực tuyến','Chọn dịch vụ và thanh toán chỉ trong vài phút.'],[Camera,'Theo dõi qua camera','Luôn thấy bé dù bạn đang ở bất cứ đâu.'],[HeartPulse,'Hồ sơ sức khỏe số','Lưu trữ lịch sử chăm sóc suốt đời.'],[Smartphone,'Báo cáo mỗi ngày','Hình ảnh và nhật ký được cập nhật liên tục.']].map(([I,t,d]:any)=><div className="solution-card" key={t}><I/><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
 <section className="innovation section"><SectionTitle eyebrow="CÔNG NGHỆ TẠO NÊN KHÁC BIỆT" title="An tâm không còn là một lời hứa" desc="Mỗi tính năng được thiết kế để tạo sự minh bạch trong từng khoảnh khắc chăm sóc."/><div className="innovation-wrap"><div className="phone-mock"><div className="phone-screen"><span>9:41</span><h4>Xin chào, Minh Anh 👋</h4><div className="pet-mini">🐱 <b>Mochi</b><small>Sức khỏe rất tốt</small></div><div className="cam-mini"><Img src="https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?auto=format&fit=crop&w=600&q=80" alt="Mochi"/><span>● LIVE</span></div></div></div><div className="innovation-list">{[[Camera,'Pet Live View','Camera theo dõi thú cưng 24/7'],[Syringe,'Smart Reminder','Nhắc vaccine, tẩy giun và tái khám'],[QrCode,'QR Emergency','Hồ sơ khẩn cấp chỉ với một lần quét'],[Hotel,'Hotel Tracking','Nhật ký lưu trú minh bạch theo thời gian thực']].map(([I,t,d]:any)=><div key={t}><span><I/></span><p><b>{t}</b><small>{d}</small></p></div>)}</div></div></section>
 <section className="section services-preview"><SectionTitle eyebrow="DỊCH VỤ CHUẨN MỰC" title="Chăm chút như chính bạn đang ở bên"/><div className="service-feature-grid">{services.map((s,i)=><div className="service-feature" key={s[0]}><Img src={s[2]} alt={s[0]}/><div><span>0{i+1}</span><h3>{s[0]}</h3><p>{s[1]}</p><Button to="/services" variant="text">Tìm hiểu thêm</Button></div></div>)}</div></section>
 <section className="promise section"><div className="promise-img"><Img src="https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1000&q=85" alt="Bác sĩ thú y"/><div><b>98%</b><span>khách hàng hài lòng</span></div></div><div><SectionTitle center={false} eyebrow="VÌ SAO CHỌN PETTECH" title="Bạn không chỉ mua dịch vụ. Bạn chọn sự an tâm."/><div className="check-list">{['Minh bạch trong từng khoảnh khắc chăm sóc','Đội ngũ chuyên môn tận tâm, giàu kinh nghiệm','Mỗi thú cưng có một hồ sơ chăm sóc riêng','Không gian sạch, an toàn và thân thiện'].map(x=><p key={x}><CheckCircle2/>{x}</p>)}</div></div></section>
 <section className="feedback-section section"><SectionTitle eyebrow="KHÁCH HÀNG NÓI GÌ" title="Những lời gửi gắm dành cho PAWFECT" desc="Mỗi phản hồi là động lực để chúng tôi chăm sóc các bé chu đáo và minh bạch hơn mỗi ngày."/><div className="feedback-grid">{feedbacks.map(([name,pet,content,initials])=><article className="feedback-card" key={name}><div className="feedback-stars" aria-label="5 sao">★★★★★</div><p>“{content}”</p><div className="feedback-author"><span>{initials}</span><div><b>{name}</b><small>{pet}</small></div></div></article>)}</div></section>
 <section className="cta-band"><div><h2>Hành trình an tâm bắt đầu từ hôm nay.</h2><p>Đặt lịch đầu tiên và trải nghiệm cách chăm sóc thú cưng hoàn toàn mới.</p></div><Button to="/login" variant="white">Đặt lịch ngay</Button></section>
 </>}
