import { useState } from 'react';
import { Activity, BarChart3, Bell, CalendarDays, Camera, CheckCircle2, CircleDollarSign, Clock3, CreditCard, HeartPulse, Home, Hotel, LogOut, PawPrint, Play, Search, Settings, Sparkles, Syringe, Users, Utensils, Video, WalletCards } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { Img } from '../components/UI';
const customerNav=[[Home,'Tổng quan & lưu trú','/customer'],[PawPrint,'Thú cưng của tôi','/customer/pets'],[HeartPulse,'Hồ sơ sức khỏe','/customer/health'],[CalendarDays,'Đặt lịch','/booking'],[Activity,'Nhật ký chăm sóc','/customer/journal'],[Camera,'Camera','/customer/camera'],[CreditCard,'Thanh toán','/customer/payments']];
const adminNav=[[BarChart3,'Tổng quan & Pet Hotel','/admin'],[CalendarDays,'Đơn hàng','/admin/orders'],[Users,'Khách hàng','/admin/customers'],[PawPrint,'Thú cưng','/admin/pets'],[CircleDollarSign,'Doanh thu','/admin/finance'],[WalletCards,'Chi phí','/admin/expenses'],[Sparkles,'Combo','/admin/memberships']];
const days=['17/06','18/06','19/06','20/06'];
const schedules:any={'17/06':[['08:00',Utensils,'Ăn sáng','80g hạt cá hồi · Ăn hết'],['10:15',Activity,'Vui chơi','Làm quen khu vận động 20 phút'],['13:00',Clock3,'Nghỉ trưa','Ngủ ngon tại phòng M-01'],['18:00',Syringe,'Vitamin','Đã dùng vitamin lông']],'18/06':[['07:30',Utensils,'Ăn sáng','Pate cá hồi 70g · Ăn hết'],['09:30',HeartPulse,'Kiểm tra sức khỏe','Nhiệt độ và nhịp thở ổn định'],['14:00',Activity,'Vui chơi','Chơi bóng 25 phút'],['18:30',Utensils,'Ăn tối','80g hạt · Ăn 90%']],'19/06':[['08:00',Utensils,'Ăn sáng','80g hạt cá hồi · Ăn hết'],['11:00',Activity,'Chải lông','Bé hợp tác, da lông tốt'],['15:30',Activity,'Vui chơi','Khu vận động 20 phút'],['20:00',Clock3,'Nghỉ tối','Đã về phòng và ngủ ngon']],'20/06':[['07:30',Utensils,'Ăn sáng','Pate 60g · Ăn hết'],['09:00',HeartPulse,'Kiểm tra trước khi về','Sức khỏe tốt'],['10:00',CheckCircle2,'Chuẩn bị check-out','Đồ dùng đã được đóng gói'],['11:00',Bell,'Đón bé','Chờ chủ nuôi tại quầy lễ tân']]};
const residents=[['Mochi','Mèo · Scottish Fold','M-01','Ngày 3/4','https://images.unsplash.com/photo-1574144611937-0df059b5ef3e'],['Bella','Chó · Poodle','D-03','Ngày 2/3','https://images.unsplash.com/photo-1583337130417-3346a1be7dee'],['Milo','Chó · Corgi','D-01','Ngày 1/5','https://images.unsplash.com/photo-1612536057832-2ff7ead58194']];
function Shell({admin=false,children}:{admin?:boolean;children:any}){const navigate=useNavigate();const links=admin?adminNav:customerNav;return <div className="dash hotel-dashboard"><aside><Link className="logo" to="/"><span><PawPrint/></span><b>PAWFECT<small>CARE CENTER</small></b></Link><p className="role">{admin?'QUẢN TRỊ VIÊN':'KHÁCH HÀNG'}</p>{links.map(([Icon,label,path]:any)=><Link className={`side-link ${path===(admin?'/admin':'/customer')?'active':''}`} to={path} key={label}><Icon/>{label}</Link>)}<div className="side-bottom"><Link className="side-link" to={admin?'/admin/settings':'/customer/settings'}><Settings/> Cài đặt</Link><button onClick={()=>{localStorage.clear();navigate('/')}}><LogOut/> Đăng xuất</button></div></aside><div className="dash-main"><div className="dash-top"><div className="dash-search"><Search/> Trung tâm theo dõi Pet Hotel</div><Bell/></div>{children}</div></div>}
function Schedule({day,editable=false}:{day:string;editable?:boolean}){const [done,setDone]=useState<Record<number,boolean>>({0:true,1:true});return <div className="panel hotel-day-panel"><div className="panel-head"><div><h3>Lịch trình ngày {day}/2026</h3><p>Ăn uống, sức khỏe, vui chơi và nghỉ ngơi</p></div><span className="hotel-live-dot">● CẬP NHẬT TRỰC TIẾP</span></div><div className="hotel-schedule">{schedules[day].map(([time,Icon,title,detail]:any,index:number)=><article className={done[index]?'completed':''} key={`${day}-${time}`}><b>{time}</b><i><Icon/></i><div><strong>{title}</strong><span>{detail}</span></div>{editable?<button onClick={()=>setDone(old=>({...old,[index]:!old[index]}))}>{done[index]?'Đã xong':'Đánh dấu xong'}</button>:<em>{done[index]?'✓ Đã hoàn thành':'Sắp tới'}</em>}</article>)}</div></div>}
function CameraPanel({room='M-01'}:{room?:string}){const [playing,setPlaying]=useState(true);return <div className="panel hotel-camera-panel"><div className="panel-head"><div><h3>Camera phòng {room}</h3><p>Luồng trực tiếp được mã hóa</p></div><span className="live">● LIVE</span></div><div className="hotel-camera-view"><Img src="https://images.unsplash.com/photo-1533743983669-94fa5c4338ec?auto=format&fit=crop&w=1000&q=85" alt="Camera Pet Hotel"/><button onClick={()=>setPlaying(!playing)}>{playing?<Video/>:<Play/>}{playing?' Đang phát trực tiếp':' Phát camera'}</button></div><div className="camera-room-tabs"><button className="active">M-01</button><button>D-03</button><button>D-01</button><button>Khu vui chơi</button></div></div>}
export function CustomerHotelTracking(){const [day,setDay]=useState('19/06');return <Shell><div className="dash-content"><div className="welcome"><div><p>PET HOTEL · MOCHI</p><h1>Theo dõi kỳ lưu trú</h1><span>Xem từng ngày, lịch ăn uống và camera của bé trong một nơi.</span></div><span className="hotel-stay-badge">● ĐANG LƯU TRÚ · PHÒNG M-01</span></div><div className="hotel-overview-card"><Img src="https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?auto=format&fit=crop&w=600&q=85" alt="Mochi"/><div><span>MÈO · SCOTTISH FOLD</span><h2>Mochi</h2><p>Check-in 17/06/2026 · Check-out 20/06/2026</p></div><div><b>Ngày 3 / 4</b><span>Còn 1 ngày</span></div></div><div className="hotel-day-tabs">{days.map(x=><button className={day===x?'active':''} onClick={()=>setDay(x)} key={x}><small>NGÀY</small><b>{x}</b>{x<'20/06'&&<span>✓ Có báo cáo</span>}</button>)}</div><div className="hotel-track-grid"><Schedule day={day}/><CameraPanel/></div></div></Shell>}
export function AdminHotelTracking(){const [pet,setPet]=useState(0);const [day,setDay]=useState('19/06');const current=residents[pet];return <Shell admin><div className="dash-content"><div className="welcome"><div><p>VẬN HÀNH PET HOTEL</p><h1>Theo dõi lưu trú</h1><span>Quản lý từng bé, lịch chăm sóc theo ngày và camera phòng.</span></div><span className="hotel-stay-badge">3 BÉ ĐANG LƯU TRÚ</span></div><div className="admin-hotel-layout"><div className="panel resident-selector"><h3>Thú cưng đang lưu trú</h3>{residents.map((x,index)=><button className={pet===index?'active':''} onClick={()=>setPet(index)} key={x[0]}><Img src={`${x[4]}?auto=format&fit=crop&w=160&q=80`} alt={x[0]}/><span><b>{x[0]}</b><small>{x[1]} · Phòng {x[2]}</small></span><em>{x[3]}</em></button>)}</div><div><div className="hotel-admin-head"><div><b>{current[0]}</b><span>{current[1]} · Phòng {current[2]}</span></div><div className="hotel-day-tabs compact">{days.map(x=><button className={day===x?'active':''} onClick={()=>setDay(x)} key={x}><b>{x}</b></button>)}</div></div><Schedule day={day} editable/></div></div><div className="hotel-admin-camera"><CameraPanel room={current[2]}/></div></div></Shell>}
