import { useEffect, useMemo, useState } from 'react';
import { BarChart3, CalendarDays, CheckCircle2, CircleDollarSign, Clock3, PawPrint, Search, Settings, Sparkles, TrendingUp, Users, WalletCards } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';

type Order={id:number;serviceType:string;date:string;time:string;note?:string;status:string;paymentStatus:string;totalPrice:number;subtotal?:number;vat?:number;hotelCheckIn?:string;hotelCheckOut?:string;hotelDays?:number;user?:{name:string};pet?:{name:string};payment?:{method:string;amount:number;status:string};demo?:boolean};
const statusText:Record<string,string>={PENDING:'Chờ xác nhận',CONFIRMED:'Đã xác nhận',IN_PROGRESS:'Đang phục vụ',COMPLETED:'Hoàn thành',CANCELLED:'Đã hủy'};
const money=(n:number)=>`${Math.round(n).toLocaleString('vi-VN')}đ`;
const nav=[[BarChart3,'Tổng quan & Pet Hotel','/admin'],[CalendarDays,'Đơn hàng','/admin/orders'],[Users,'Khách hàng','/admin/customers'],[PawPrint,'Thú cưng','/admin/pets'],[CircleDollarSign,'Doanh thu','/admin/finance'],[WalletCards,'Chi phí','/admin/expenses'],[Sparkles,'Combo','/admin/memberships'],[TrendingUp,'Analytics','/admin/analytics']];
const samples:Order[]=[
  {id:-1001,user:{name:'Nguyễn Minh Anh'},pet:{name:'Mochi'},serviceType:'Grooming · Gold × 1',date:'2026-06-20',time:'09:30',status:'CONFIRMED',paymentStatus:'PAID',totalPrice:236520,payment:{method:'MoMo',amount:236520,status:'PAID'},demo:true},
  {id:-1002,user:{name:'Quang Huy'},pet:{name:'Bella'},serviceType:'Pet Hotel · Gold × 3 ngày',date:'2026-06-20',time:'08:00',hotelCheckIn:'2026-06-20',hotelCheckOut:'2026-06-23',hotelDays:3,subtotal:1167000,vat:93360,status:'IN_PROGRESS',paymentStatus:'PAID',totalPrice:1260360,payment:{method:'ZaloPay',amount:1260360,status:'PAID'},demo:true},
  {id:-1003,user:{name:'Thảo Vy'},pet:{name:'Bông'},serviceType:'Spa · Premium × 1',date:'2026-06-19',time:'13:30',status:'COMPLETED',paymentStatus:'PAID',totalPrice:452520,payment:{method:'Thẻ ngân hàng',amount:452520,status:'PAID'},demo:true},
  {id:-1004,user:{name:'Mai Linh'},pet:{name:'Mây'},serviceType:'Combo Sạch Xinh · Combo × 1',date:'2026-06-21',time:'15:00',status:'PENDING',paymentStatus:'UNPAID',totalPrice:301320,payment:{method:'Tiền mặt tại cửa hàng',amount:301320,status:'UNPAID'},demo:true},
  {id:-1005,user:{name:'Tuấn Khang'},pet:{name:'Milo'},serviceType:'Combo Khỏe & Đẹp · Combo × 1',date:'2026-06-22',time:'11:00',status:'CONFIRMED',paymentStatus:'PAID',totalPrice:506520,payment:{method:'MoMo',amount:506520,status:'PAID'},demo:true}
];

export default function LiveAdminOrders(){
  const [liveOrders,setLiveOrders]=useState<Order[]>([]); const [query,setQuery]=useState(''); const [status,setStatus]=useState('Tất cả'); const [selected,setSelected]=useState<Order|null>(null);
  const [demoStatus,setDemoStatus]=useState<Record<number,string>>({});
  useEffect(()=>{api('/bookings').then(setLiveOrders).catch(()=>setLiveOrders([]))},[]);
  const orders=[...liveOrders,...samples.map(x=>({...x,status:demoStatus[x.id]||x.status}))];
  const shown=orders.filter(x=>(status==='Tất cả'||statusText[x.status]===status)&&`${x.id} ${x.user?.name} ${x.pet?.name} ${x.serviceType}`.toLowerCase().includes(query.toLowerCase()));
  const summary=useMemo(()=>({total:orders.reduce((sum,x)=>sum+x.totalPrice,0),pending:orders.filter(x=>x.status==='PENDING').length,active:orders.filter(x=>['CONFIRMED','IN_PROGRESS'].includes(x.status)).length,done:orders.filter(x=>x.status==='COMPLETED').length}),[liveOrders,demoStatus]);
  const updateStatus=async(order:Order,next:string)=>{if(order.demo){setDemoStatus(old=>({...old,[order.id]:next}));return}setLiveOrders(old=>old.map(x=>x.id===order.id?{...x,status:next}:x));try{await api(`/bookings/${order.id}`,{method:'PUT',body:JSON.stringify({status:next})})}catch{}};
  const code=(order:Order)=>order.demo?`PT-${String(Math.abs(order.id)).slice(-4)}`:`PF-${String(order.id).padStart(5,'0')}`;
  return <div className="dash admin-system"><aside><Link className="logo" to="/"><span><PawPrint/></span><b>PAWFECT<small>CARE CENTER</small></b></Link><p className="role">QUẢN TRỊ VIÊN</p>{nav.map(([Icon,label,path]:any)=><Link className={`side-link ${label==='Đơn hàng'?'active':''}`} to={path} key={label}><Icon/>{label}</Link>)}<div className="side-bottom"><Link className="side-link" to="/admin/settings"><Settings/> Cài đặt hệ thống</Link></div></aside><div className="dash-main"><div className="dash-top"><div className="dash-search"><Search/>Tìm kiếm trong hệ thống...</div></div><div className="dash-content">
    <div className="welcome admin-head"><div><p>VẬN HÀNH</p><h1>Quản lý đơn hàng</h1><span>Đơn thật được đồng bộ từ giỏ hàng và hiển thị cùng dữ liệu mẫu vận hành.</span></div></div>
    <div className="order-kpis"><article><span><CalendarDays/></span><small>Tổng đơn hàng</small><b>{orders.length}</b><em>Gồm {liveOrders.length} đơn thực tế</em></article><article><span><CircleDollarSign/></span><small>Tổng giá trị đơn hàng</small><b>{money(summary.total)}</b><em>Đã bao gồm VAT 8%</em></article><article><span><Clock3/></span><small>Chờ / đang xử lý</small><b>{summary.pending+summary.active}</b><em>{summary.pending} đơn chờ xác nhận</em></article><article><span><CheckCircle2/></span><small>Đã hoàn thành</small><b>{summary.done}</b><em>Đơn phục vụ thành công</em></article></div>
    <div className="admin-filter"><div><Search/><input placeholder="Tìm mã đơn, khách hàng, thú cưng..." value={query} onChange={e=>setQuery(e.target.value)}/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>Tất cả</option><option>Chờ xác nhận</option><option>Đã xác nhận</option><option>Đang phục vụ</option><option>Hoàn thành</option><option>Đã hủy</option></select></div>
    <div className="panel admin-table"><table><thead><tr><th>Mã đơn</th><th>Khách hàng</th><th>Thú cưng</th><th>Dịch vụ / combo · số lượng</th><th>Lịch Pet Hotel</th><th>Tiền dịch vụ</th><th>VAT 8%</th><th>Tổng cộng</th><th>Thanh toán</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{shown.map(order=>{const subtotal=order.subtotal??Math.round(order.totalPrice/1.08);const vat=order.vat??Math.round(order.totalPrice-subtotal);return <tr key={`${order.demo?'d':'r'}-${order.id}`}><td><b>{code(order)}</b>{order.demo&&<small className="sample-label">MẪU</small>}</td><td>{order.user?.name||'Khách hàng'}</td><td>{order.pet?.name||'—'}</td><td>{order.serviceType}</td><td>{order.hotelDays?<span className="hotel-order-range"><b>{order.hotelDays} ngày</b><small>{order.hotelCheckIn} → {order.hotelCheckOut}</small></span>:'—'}</td><td>{money(subtotal)}</td><td>{money(vat)}</td><td><b>{money(order.totalPrice)}</b></td><td><span className={`payment-state ${order.paymentStatus==='PAID'?'paid':'unpaid'}`}>{order.paymentStatus==='PAID'?'Đã thanh toán':'Chưa thanh toán'}</span></td><td><select className={`order-status status-${order.status.toLowerCase()}`} value={order.status} onChange={e=>updateStatus(order,e.target.value)}><option value="PENDING">Chờ xác nhận</option><option value="CONFIRMED">Đã xác nhận</option><option value="IN_PROGRESS">Đang phục vụ</option><option value="COMPLETED">Hoàn thành</option><option value="CANCELLED">Đã hủy</option></select></td><td><button onClick={()=>setSelected(order)}>Chi tiết</button></td></tr>})}</tbody></table>{!shown.length&&<div className="admin-empty">Không tìm thấy đơn hàng phù hợp.</div>}</div>
  </div></div>{selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="admin-detail-modal" onClick={e=>e.stopPropagation()}><button onClick={()=>setSelected(null)}>×</button><span className="eyebrow">CHI TIẾT ĐƠN HÀNG</span><h2>{code(selected)}</h2><div><p><span>Khách hàng</span><b>{selected.user?.name}</b></p><p><span>Thú cưng</span><b>{selected.pet?.name}</b></p><p><span>Dịch vụ / combo</span><b>{selected.serviceType}</b></p>{selected.hotelDays&&<><p><span>Ngày nhận bé</span><b>{selected.hotelCheckIn}</b></p><p><span>Ngày trả bé</span><b>{selected.hotelCheckOut}</b></p><p><span>Số ngày lưu trú</span><b>{selected.hotelDays} ngày</b></p></>}<p><span>Lịch hẹn</span><b>{selected.time} · {selected.date}</b></p><p><span>Tiền dịch vụ</span><b>{money(selected.subtotal??selected.totalPrice/1.08)}</b></p><p><span>VAT 8%</span><b>{money(selected.vat??selected.totalPrice-selected.totalPrice/1.08)}</b></p><p><span>Tổng thanh toán</span><b>{money(selected.totalPrice)}</b></p><p><span>Phương thức</span><b>{selected.payment?.method||'Chưa ghi nhận'}</b></p><p><span>Trạng thái</span><b>{statusText[selected.status]}</b></p><p><span>Ghi chú</span><b>{selected.note||'Không có'}</b></p></div><div className="admin-detail-actions"><button className="btn primary" onClick={()=>setSelected(null)}>Hoàn tất</button></div></div></div>}</div>;
}
