import { useParams } from 'react-router-dom';
import { BookOpen, CalendarDays, Check, ChevronRight, Clock3, Heart, Hotel, Scissors, Shield, Sparkles, Stethoscope, Truck, Video } from 'lucide-react';
import { Button, Img, SectionTitle } from '../components/UI';

export const serviceData=[
 {slug:'grooming',name:'Grooming',desc:'Tắm, sấy, vệ sinh và cắt tỉa theo giống.',icon:Scissors,image:'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=1000&q=85',duration:'60–120 phút',tiers:[['Silver','119.000đ','Tắm, sấy, vệ sinh tai và cắt móng'],['Gold','219.000đ','Silver + cắt tỉa tạo kiểu, dưỡng lông'],['Premium','319.000đ','Gold + massage, phục hồi lông chuyên sâu']]},
 {slug:'spa',name:'Spa cao cấp',desc:'Massage thư giãn, chăm sóc da và phục hồi lông.',icon:Sparkles,image:'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1000&q=85',duration:'75–120 phút',tiers:[['Silver','199.000đ','Tắm thảo mộc và massage 15 phút'],['Gold','299.000đ','Silver + ủ dưỡng da lông chuyên sâu'],['Premium','419.000đ','Gold + liệu trình phục hồi và xịt dưỡng cao cấp']]},
 {slug:'pet-hotel',name:'Pet Hotel',desc:'Phòng riêng tiện nghi, camera và báo cáo mỗi ngày.',icon:Hotel,image:'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=1000&q=85',duration:'Theo ngày / đêm',tiers:[['Silver','289.000đ/ngày','Phòng tiêu chuẩn, 2 bữa và 1 lần vui chơi'],['Gold','389.000đ/ngày','Phòng rộng, camera 24/7 và 2 lần vui chơi'],['Premium','519.000đ/ngày','Phòng VIP, báo cáo 3 lần/ngày, chăm sóc 1:1']]},
 {slug:'health-care',name:'Chăm sóc sức khỏe',desc:'Khám tổng quát và tư vấn phòng bệnh cơ bản.',icon:Stethoscope,image:'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1000&q=85',duration:'30–60 phút',tiers:[['Silver','189.000đ','Khám tổng quát cơ bản'],['Gold','299.000đ','Khám tổng quát + tư vấn dinh dưỡng'],['Premium','499.000đ','Gold + xét nghiệm cơ bản và hồ sơ sức khỏe số']]},
 {slug:'transport',name:'Đưa đón tận nơi',desc:'Xe chuyên dụng an toàn, định vị hành trình.',icon:Truck,image:'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=1000&q=85',duration:'30–90 phút',tiers:[['Silver','79.000đ','Một chiều trong bán kính 5km'],['Gold','139.000đ','Hai chiều trong bán kính 5km'],['Premium','219.000đ','Hai chiều trong bán kính 10km, ưu tiên giờ']]},
 {slug:'online-consultation',name:'Tư vấn trực tuyến',desc:'Kết nối chuyên gia chăm sóc qua video call.',icon:Video,image:'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=1000&q=85',duration:'20–45 phút',tiers:[['Silver','99.000đ','Tư vấn nhanh 20 phút'],['Gold','179.000đ','Tư vấn 30 phút + kế hoạch chăm sóc'],['Premium','279.000đ','Tư vấn 45 phút + theo dõi sau 7 ngày']]}
];

export function Services(){return <><PageHero tag="DỊCH VỤ PETTECH" title="Một điểm đến, trọn vẹn yêu thương" desc="Xem rõ quy trình, thời gian và chọn cấp độ chăm sóc phù hợp cho từng bé."/><section className="section"><div className="services-grid">{serviceData.map(s=>{const I=s.icon;return <article className="service-card" key={s.slug}><div className="service-image"><Img src={s.image} alt={s.name}/><span><I/></span></div><div><h3>{s.name}</h3><p>{s.desc}</p><p className="duration"><Clock3/> {s.duration}</p><b>Từ {s.tiers[0][1]}</b><Button to={`/services/${s.slug}`} variant="text">Xem chi tiết</Button></div></article>})}</div></section></>}

export function ServiceDetail(){const {slug}=useParams();const s=serviceData.find(x=>x.slug===slug)||serviceData[0];const I=s.icon;return <><section className="service-detail-hero"><div><span className="eyebrow">DỊCH VỤ PETTECH</span><h1>{s.name}</h1><p>{s.desc} Mỗi bước đều được ghi nhận để chủ nuôi dễ dàng theo dõi.</p><div><span><Clock3/> {s.duration}</span><span><Shield/> Quy trình an toàn</span></div><Button to="/booking">Chọn dịch vụ này</Button></div><Img src={s.image} alt={s.name}/></section><section className="section detail-process"><SectionTitle eyebrow="QUY TRÌNH DỊCH VỤ" title="Bé sẽ được chăm sóc như thế nào?"/><div className="four-grid">{[['01','Tiếp nhận & tư vấn','Kiểm tra tình trạng, thói quen và ghi nhận yêu cầu riêng.'],['02','Thực hiện dịch vụ','Chuyên viên tiến hành theo đúng cấp độ đã chọn.'],['03','Kiểm tra chất lượng','Đánh giá kết quả, sức khỏe và mức độ thoải mái của bé.'],['04','Bàn giao & báo cáo','Gửi hình ảnh, lưu hồ sơ và hướng dẫn chăm sóc tại nhà.']].map(x=><div className="number-card"><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section><section className="section tier-section"><SectionTitle eyebrow="3 CẤP ĐỘ CHĂM SÓC" title={`Chọn gói ${s.name} phù hợp`}/><div className="tier-grid">{s.tiers.map((t,i)=><div className={i===1?'tier featured':'tier'}><span>{i===1?'ĐƯỢC CHỌN NHIỀU':'GÓI DỊCH VỤ'}</span><I/><h3>{t[0]}</h3><b>{t[1]}</b><p>{t[2]}</p><ul><li><Check/> Tư vấn trước dịch vụ</li><li><Check/> Ảnh cập nhật sau hoàn thành</li><li><Check/> Lưu vào hồ sơ chăm sóc</li></ul><Button to="/booking" variant={i===1?'primary':'outline'}>Chọn {t[0]}</Button></div>)}</div></section></>}

export function Pricing(){return <><PageHero tag="BẢNG GIÁ THEO CẤP ĐỘ" title="Chọn đúng mức chăm sóc, trả đúng giá trị" desc="Silver tiết kiệm cho nhu cầu cơ bản, Gold cân bằng quyền lợi, Premium dành cho trải nghiệm toàn diện."/><section className="section pricing-detail"><div className="pricing-legend"><span><b>Silver</b> Tiết kiệm, đủ nhu cầu cơ bản</span><span><b>Gold</b> Nâng cao, được chọn nhiều nhất</span><span><b>Premium</b> Chăm sóc toàn diện</span></div>{serviceData.map(s=>{const I=s.icon;return <div className="pricing-service"><div className="pricing-name"><I/><div><h3>{s.name}</h3><p>{s.duration}</p></div><Button to={`/services/${s.slug}`} variant="text">Xem chi tiết</Button></div><div className="pricing-tiers">{s.tiers.map((t,i)=><div className={i===1?'best':''}><span>{t[0]}</span><b>{t[1]}</b><p>{t[2]}</p><Button to="/booking" variant={i===1?'primary':'outline'}>Chọn gói</Button></div>)}</div></div>})}</section></>}

const combos=[
 ['Combo Sạch Xinh','Grooming Silver + Spa Silver','219.000đ','238.000đ','Tiết kiệm 19.000đ'],
 ['Combo Tỏa Sáng','Grooming Gold + Spa Gold','479.000đ','518.000đ','Tiết kiệm 39.000đ'],
 ['Combo Kỳ Nghỉ An Tâm','3 ngày Pet Hotel Gold + 1 Grooming Gold','1.349.000đ','1.386.000đ','Tiết kiệm 37.000đ'],
 ['Combo Khỏe & Đẹp','Sản phẩm tẩy giun phổ thông theo hướng dẫn nhà sản xuất + Grooming Gold','249.000đ','308.000đ','Tiết kiệm 59.000đ'],
 ['Combo Premium Day','Grooming Premium + Spa Premium + sản phẩm tẩy giun phổ thông theo hướng dẫn nhà sản xuất','739.000đ','827.000đ','Tiết kiệm 88.000đ']
];
export function Membership(){return <><PageHero tag="COMBO CHĂM SÓC" title="Kết hợp nhiều dịch vụ, tiết kiệm nhiều hơn" desc="Không cần mua membership khó hiểu — chọn combo theo đúng nhu cầu và thời gian chăm sóc của bé."/><section className="section combo-section"><SectionTitle eyebrow="COMBO DỊCH VỤ" title="Một lần đặt, trọn gói yêu thương"/><div className="combo-grid">{combos.map((c,i)=><div className={i===1?'combo featured':'combo'}><span>{i===1?'PHỔ BIẾN':'COMBO'}</span><h3>{c[0]}</h3><p>{c[1]}</p><div><b>{c[2]}</b><del>{c[3]}</del></div><em>{c[4]}</em><Button to="/booking" variant={i===1?'primary':'outline'}>Chọn combo</Button></div>)}</div></section><section className="section duration-plans"><SectionTitle eyebrow="ĐĂNG KÝ THEO KỲ" title="Càng đồng hành lâu, giá càng tốt" desc="Áp dụng cho mọi combo chăm sóc định kỳ; quyền lợi được sử dụng linh hoạt trong thời hạn."/><div className="duration-grid">{[['3 tháng','Giảm 5%','Tặng 1 lần tư vấn online'],['6 tháng','Giảm 10%','Tặng 1 lần đưa đón một chiều'],['12 tháng','Giảm 15%','Tặng 1 Grooming Silver + ưu tiên lịch']].map((x,i)=><div className={i===2?'featured':''}><CalendarDays/><h3>{x[0]}</h3><b>{x[1]}</b><p>{x[2]}</p><Button to="/booking" variant={i===2?'primary':'outline'}>Đăng ký</Button></div>)}</div></section></>}

export const articles=[
 {slug:'vaccine-cho-cho-meo',title:'Vaccine cho chó mèo',category:'Sức khỏe',summary:'Lịch vaccine nền tảng giúp bé khỏe mạnh qua từng giai đoạn.',image:'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=1000&q=85',content:['Vaccine giúp hệ miễn dịch nhận biết và chống lại những bệnh truyền nhiễm nguy hiểm. Với chó con và mèo con, lịch tiêm thường bắt đầu khi bé đủ 6–8 tuần tuổi.','Trước khi tiêm, bé cần khỏe mạnh, không sốt, không tiêu chảy và đã được tẩy giun theo hướng dẫn. Sau tiêm nên theo dõi 24–48 giờ; nếu bé khó thở, sưng mặt hoặc nôn liên tục, hãy liên hệ bác sĩ thú y ngay.','Mỗi bé có thể cần lịch khác nhau tùy tuổi, tiền sử và môi trường sống. Hồ sơ sức khỏe điện tử PetTech sẽ lưu ngày tiêm và tự động nhắc mũi tiếp theo.']},
 {slug:'dinh-duong-theo-do-tuoi',title:'Dinh dưỡng theo độ tuổi',category:'Dinh dưỡng',summary:'Cách xây dựng khẩu phần cân bằng cho chó mèo.',image:'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=1000&q=85',content:['Nhu cầu năng lượng thay đổi rõ rệt giữa giai đoạn sơ sinh, trưởng thành và cao tuổi. Thức ăn phù hợp độ tuổi giúp kiểm soát cân nặng và hỗ trợ hệ tiêu hóa.','Không thay đổi thức ăn đột ngột. Hãy chuyển đổi trong 5–7 ngày và luôn chuẩn bị nước sạch.']},
 {slug:'benh-thuong-gap',title:'Các bệnh thường gặp',category:'Sức khỏe',summary:'Dấu hiệu sớm mà mỗi chủ nuôi nên nhận biết.',image:'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=1000&q=85',content:['Bỏ ăn, mệt mỏi, nôn, tiêu chảy hoặc thay đổi hành vi có thể là những tín hiệu sớm. Quan sát và ghi lại diễn biến giúp bác sĩ chẩn đoán chính xác hơn.','Không tự ý dùng thuốc của người cho thú cưng. Khi triệu chứng kéo dài hoặc trở nặng, cần đưa bé đi khám.']},
 {slug:'cham-soc-sau-spa',title:'Chăm sóc thú cưng sau spa',category:'Chăm sóc',summary:'Giữ bộ lông sạch đẹp và làn da khỏe lâu hơn.',image:'https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1000&q=85',content:['Sau spa, giữ bé ở nơi khô ráo và hạn chế lăn trên nền bẩn. Chải lông nhẹ mỗi ngày giúp ngăn rối và phân bố dầu tự nhiên.','Theo dõi biểu hiện ngứa, đỏ da hoặc liếm quá mức và báo lại cho chuyên viên nếu có bất thường.']},
 {slug:'luu-y-pet-hotel',title:'Lưu ý khi gửi Pet Hotel',category:'Lưu trú',summary:'Checklist giúp bé thích nghi nhanh với kỳ nghỉ.',image:'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=1000&q=85',content:['Chuẩn bị thức ăn quen thuộc, thuốc đang dùng và một món đồ có mùi của chủ nuôi. Cung cấp đầy đủ thông tin về tính cách, thói quen và dị ứng.','Nên cho bé làm quen không gian trước kỳ lưu trú dài và đảm bảo vaccine còn hiệu lực.']},
 {slug:'nuoi-thu-cung-khoa-hoc',title:'Nuôi thú cưng khoa học',category:'Đời sống',summary:'Những nguyên tắc nhỏ tạo nên cuộc sống hạnh phúc.',image:'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1000&q=85',content:['Một lịch sinh hoạt ổn định, vận động phù hợp và khám định kỳ là nền tảng của cuộc sống khỏe mạnh.','Dành thời gian tương tác mỗi ngày giúp bé giảm căng thẳng và xây dựng mối liên kết bền vững với gia đình.']}
];
export function Knowledge(){return <><PageHero tag="THƯ VIỆN KIẾN THỨC" title="Hiểu đúng để yêu thương tốt hơn" desc="Nội dung chọn lọc từ đội ngũ chăm sóc và chuyên gia thú y PetTech."/><section className="section article-grid">{articles.map(a=><article key={a.slug}><Img src={a.image} alt={a.title} className="article-image"/><span>{a.category}</span><h3>{a.title}</h3><p>{a.summary}</p><Button to={`/knowledge/${a.slug}`} variant="text">Đọc bài viết</Button></article>)}</section></>}
export function ArticleDetail(){const {slug}=useParams();const a=articles.find(x=>x.slug===slug)||articles[0];return <article className="article-detail"><div className="article-heading"><span>{a.category}</span><h1>{a.title}</h1><p>{a.summary}</p></div><Img src={a.image} alt={a.title}/><div className="article-body"><p className="lead">Kiến thức thiết thực để bạn chủ động chăm sóc người bạn nhỏ khỏe mạnh và hạnh phúc hơn mỗi ngày.</p>{a.content.map((p,i)=><p key={i}>{p}</p>)}<div className="article-tip"><BookOpen/><p><b>Lưu ý từ PetTech</b><br/>Nội dung mang tính tham khảo. Khi thú cưng có biểu hiện bất thường, hãy liên hệ bác sĩ thú y.</p></div><Button to="/knowledge" variant="outline">Quay lại thư viện</Button></div></article>}

export function About(){return <><PageHero tag="VỀ PETTECH" title="Công nghệ nâng niu những điều bạn yêu" desc="Chúng tôi xây dựng hệ sinh thái nơi mọi thú cưng được thấu hiểu và mọi chủ nuôi luôn an tâm."/><section className="section about-story"><Img src="https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1100&q=85" alt="Câu chuyện PetTech"/><div><SectionTitle center={false} eyebrow="SỨ MỆNH" title="Minh bạch, tiện lợi và cá nhân hóa" desc="Giúp chủ nuôi an tâm hơn bằng một hệ sinh thái chăm sóc thú cưng kết hợp chuyên môn, sự tận tâm và công nghệ."/><p>Tầm nhìn của PetTech là trở thành nền tảng chăm sóc thú cưng thông minh hàng đầu Việt Nam, vận hành đúng quy định pháp lý, dựa trên khoa học thú y và có khả năng triển khai thực tế.</p></div></section><section className="section values"><SectionTitle eyebrow="GIÁ TRỊ CỐT LÕI" title="Điều dẫn lối cho mọi hành động"/><div className="three-grid">{[[Shield,'An toàn','Quy trình tiêu chuẩn và dữ liệu bảo mật.'],[Heart,'Tận tâm','Đối xử với mỗi bé như một thành viên gia đình.'],[Sparkles,'Đổi mới','Công nghệ giải quyết nhu cầu thật của chủ nuôi.']].map(([I,t,d]:any)=><div><I/><h3>{t}</h3><p>{d}</p></div>)}</div></section></>}
export function PageHero({tag,title,desc}:{tag:string,title:string,desc:string}){return <section className="page-hero"><span>{tag}</span><h1>{title}</h1><p>{desc}</p></section>}
