import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Bell, CalendarDays, ClipboardList, Clock3, Home, Hotel, LogOut, PackageOpen, PawPrint, Search, Settings, UserRound } from 'lucide-react';
import { productGroups } from './CommercePages';
import { changeStock, readInventory } from '../components/inventoryStore';

const menu=[[Home,'Tổng quan'],[CalendarDays,'Booking hôm nay'],[PawPrint,'Check-in / Check-out'],[ClipboardList,'Nhật ký chăm sóc'],[Hotel,'Pet Hotel'],[PackageOpen,'Kho sản phẩm'],[Clock3,'Ca làm'],[UserRound,'Hồ sơ nhân viên']];
const products=productGroups.flatMap(g=>g.items.map((x:any[])=>({id:Number(x[0]),category:g.title,name:String(x[2]),unit:String(x[3]),price:Number(x[4])})));
const money=(n:number)=>`${n.toLocaleString('vi-VN')}đ`;

export default function StaffInventory(){
 const navigate=useNavigate();
 const [data,setData]=useState(readInventory);const [query,setQuery]=useState('');const [notice,setNotice]=useState('');
 const shown=products.filter(x=>`${x.name} ${x.category}`.toLowerCase().includes(query.toLowerCase()));
 const adjust=(id:number,delta:number)=>{setData(changeStock(id,delta));setNotice(`Đã ${delta>0?'nhập':'xuất'} ${Math.abs(delta)} sản phẩm SP-${id}`)};
 const openPage=(label:string)=>{if(label!=='Kho sản phẩm')navigate('/staff')};
 return <div className="dash staff-portal"><aside><Link className="logo" to="/"><span><PawPrint/></span><b>PAWFECT<small>STAFF CENTER</small></b></Link><p className="role">NHÂN VIÊN CHĂM SÓC</p>{menu.map(([Icon,label]:any)=><button className={label==='Kho sản phẩm'?'active':''} onClick={()=>openPage(label)} key={label}><Icon/>{label}</button>)}<div className="side-bottom"><button onClick={()=>navigate('/staff')}><Settings/> Cài đặt</button><button onClick={()=>{localStorage.clear();navigate('/')}}><LogOut/> Đăng xuất</button></div></aside><div className="dash-main"><div className="dash-top"><div className="dash-search"><Search/> Tìm sản phẩm trong kho...</div><Bell/><div className="dash-user"><span>LA</span><p><b>Lan Anh</b><small>Ca sáng · 07:00–15:00</small></p></div></div><div className="dash-content"><div className="welcome"><div><p>KHO SẢN PHẨM</p><h1>Nhập · xuất kho trong ca</h1><span>Kiểm tra tồn kho, lượt bán và cập nhật số lượng thực tế tại quầy.</span></div></div>{notice&&<div className="notice">✓ {notice}</div>}<div className="staff-inventory-summary"><div><PackageOpen/><span>Đang còn<b>{Object.values(data.stock).reduce((a,b)=>a+b,0)} sản phẩm</b></span></div><div><CalendarDays/><span>Đã bán<b>{Object.values(data.sold).reduce((a,b)=>a+b,0)} lượt</b></span></div><div><Clock3/><span>Doanh thu sản phẩm<b>{money(Object.values(data.revenue).reduce((a,b)=>a+b,0))}</b></span></div></div><section className="panel admin-table staff-inventory-table"><div className="panel-head"><div><h3>Danh sách sản phẩm</h3><p>Staff được nhập và xuất số lượng thực tế</p></div><label className="inventory-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm sản phẩm..."/></label></div><table><thead><tr><th>Mã</th><th>Sản phẩm</th><th>Nhóm</th><th>Tồn kho</th><th>Đã bán</th><th>Doanh thu</th><th>Thao tác kho</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><b>SP-{x.id}</b></td><td><b>{x.name}</b><small>{x.unit} · {money(x.price)}</small></td><td>{x.category}</td><td><span className={`inventory-stock ${(data.stock[x.id]||0)<=5?'low':''}`}>{data.stock[x.id]||0}</span></td><td>{data.sold[x.id]||0}</td><td><b>{money(data.revenue[x.id]||0)}</b></td><td><div className="inventory-adjust"><button onClick={()=>adjust(x.id,-1)}>Xuất 1</button><button onClick={()=>adjust(x.id,1)}>Nhập 1</button><button onClick={()=>adjust(x.id,10)}>Nhập 10</button></div></td></tr>)}</tbody></table></section></div></div></div>
}
