import express from 'express';import cors from 'cors';import dotenv from 'dotenv';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import path from 'node:path';import {PrismaClient} from '@prisma/client';
dotenv.config();const app=express();const prisma=new PrismaClient();const secret=process.env.JWT_SECRET||'pettech-demo-secret';app.use(cors());app.use(express.json());
type Req=express.Request&{user?:any};const auth=async(req:Req,res:express.Response,next:express.NextFunction)=>{try{const token=req.headers.authorization?.replace('Bearer ','');if(!token)return res.status(401).json({message:'Vui lòng đăng nhập'});req.user=jwt.verify(token,secret);next()}catch{return res.status(401).json({message:'Phiên đăng nhập không hợp lệ'})}};
app.get('/api/health',(_,res)=>res.json({status:'ok',service:'PAWFECT API'}));
app.post('/api/auth/register',async(req,res,next)=>{try{const{name,email,phone,password,confirm}=req.body;if(!name||!email||!password)return res.status(400).json({message:'Vui lòng nhập đủ thông tin'});if(confirm&&password!==confirm)return res.status(400).json({message:'Mật khẩu xác nhận không khớp'});const user=await prisma.user.create({data:{name,email,phone,password:await bcrypt.hash(password,10)}});const token=jwt.sign({id:user.id,role:user.role},secret,{expiresIn:'7d'});res.status(201).json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role}})}catch(e:any){if(e.code==='P2002')return res.status(409).json({message:'Email đã được sử dụng'});next(e)}});
app.post('/api/auth/login',async(req,res)=>{const user=await prisma.user.findUnique({where:{email:req.body.email}});if(!user||!await bcrypt.compare(req.body.password,user.password))return res.status(401).json({message:'Email hoặc mật khẩu chưa đúng'});const token=jwt.sign({id:user.id,role:user.role},secret,{expiresIn:'7d'});res.json({token,user:{id:user.id,name:user.name,email:user.email,role:user.role}})});
app.get('/api/auth/me',auth,async(req:Req,res)=>{const user=await prisma.user.findUnique({where:{id:req.user.id},select:{id:true,name:true,email:true,phone:true,role:true}});res.json(user)});
app.get('/api/pets',auth,async(req:Req,res)=>res.json(await prisma.pet.findMany({where:req.user.role==='CUSTOMER'?{ownerId:req.user.id}:{},include:{healthRecords:true,hotelStays:true}})));
app.get('/api/pets/:id',auth,async(req,res)=>res.json(await prisma.pet.findUnique({where:{id:+req.params.id},include:{healthRecords:true,journals:true,hotelStays:true}})));
app.post('/api/pets',auth,async(req:Req,res)=>res.status(201).json(await prisma.pet.create({data:{...req.body,ownerId:req.user.id}})));
app.put('/api/pets/:id',auth,async(req,res)=>res.json(await prisma.pet.update({where:{id:+req.params.id},data:req.body})));
app.delete('/api/pets/:id',auth,async(req,res)=>{await prisma.pet.delete({where:{id:+req.params.id}});res.json({message:'Đã xóa thú cưng'})});
app.get('/api/health-records/:petId',auth,async(req,res)=>res.json(await prisma.healthRecord.findMany({where:{petId:+req.params.petId}})));
app.post('/api/health-records',auth,async(req,res)=>res.status(201).json(await prisma.healthRecord.create({data:req.body})));
app.put('/api/health-records/:id',auth,async(req,res)=>res.json(await prisma.healthRecord.update({where:{id:+req.params.id},data:req.body})));
app.delete('/api/health-records/:id',auth,async(req,res)=>{await prisma.healthRecord.delete({where:{id:+req.params.id}});res.json({message:'Đã xóa hồ sơ'})});
app.get('/api/bookings',auth,async(req:Req,res)=>res.json(await prisma.booking.findMany({where:req.user.role==='CUSTOMER'?{userId:req.user.id}:{},include:{pet:true,user:{select:{name:true}},payment:true},orderBy:{createdAt:'desc'}})));
app.post('/api/bookings',auth,async(req:Req,res)=>{let pet=await prisma.pet.findFirst({where:{ownerId:req.user.id}});if(!pet)pet=await prisma.pet.create({data:{ownerId:req.user.id,name:req.body.pet||'Mochi',species:'Mèo',breed:'Scottish Fold'}});res.status(201).json(await prisma.booking.create({data:{userId:req.user.id,petId:pet.id,serviceType:req.body.service,date:req.body.date,time:req.body.time,note:req.body.note,totalPrice:req.body.totalPrice||150000,status:'CONFIRMED',paymentStatus:'PAID'}}))});
app.put('/api/bookings/:id',auth,async(req,res)=>res.json(await prisma.booking.update({where:{id:+req.params.id},data:req.body})));
app.delete('/api/bookings/:id',auth,async(req,res)=>{await prisma.booking.delete({where:{id:+req.params.id}});res.json({message:'Đã hủy lịch'})});
app.post('/api/payments',auth,async(req,res)=>{const p=await prisma.payment.create({data:req.body});await prisma.booking.update({where:{id:req.body.bookingId},data:{status:'CONFIRMED',paymentStatus:'PAID'}});res.status(201).json(p)});
app.get('/api/care-journals/:petId',auth,async(req,res)=>res.json(await prisma.careJournal.findMany({where:{petId:+req.params.petId},orderBy:{date:'desc'}})));
app.post('/api/care-journals',auth,async(req,res)=>res.status(201).json(await prisma.careJournal.create({data:req.body})));
app.put('/api/care-journals/:id',auth,async(req,res)=>res.json(await prisma.careJournal.update({where:{id:+req.params.id},data:req.body})));
app.get('/api/hotel-stays',auth,async(_,res)=>res.json(await prisma.petHotelStay.findMany({include:{pet:true}})));
app.post('/api/hotel-stays',auth,async(req,res)=>res.status(201).json(await prisma.petHotelStay.create({data:req.body})));
app.put('/api/hotel-stays/:id',auth,async(req,res)=>res.json(await prisma.petHotelStay.update({where:{id:+req.params.id},data:req.body})));
app.get('/api/memberships',auth,async(req:Req,res)=>res.json(await prisma.membership.findMany({where:req.user.role==='CUSTOMER'?{userId:req.user.id}:{}})));
app.post('/api/memberships',auth,async(req:Req,res)=>res.status(201).json(await prisma.membership.create({data:{...req.body,userId:req.user.id}})));
app.get('/api/admin/analytics',auth,(_,res)=>res.json({revenue:[210,260,245,330,390,472],bookings:1248,customers:862,pets:1036,occupancy:78,returningRate:64,topServices:['Pet Hotel','Grooming','Spa']}));
app.get('/api/articles',async(_,res)=>res.json(await prisma.knowledgeArticle.findMany()));
const clientDist=path.resolve(process.cwd(),'../client/dist');
app.use(express.static(clientDist));
app.use((req,res,next)=>{if(req.method==='GET'&&!req.path.startsWith('/api'))return res.sendFile(path.join(clientDist,'index.html'));next()});
app.use((err:any,_:any,res:any,__:any)=>{console.error(err);res.status(500).json({message:'Máy chủ gặp lỗi, vui lòng thử lại'})});
app.listen(Number(process.env.PORT)||4000,()=>console.log('🐾 PAWFECT API: http://localhost:4000'));
